# Generated by Django 6.1.1 on 2026-09-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='player.listener')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='player.track')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('listener', 'track'), name='unique_favourite')],
            },
        ),
    ]
