# Generated by Django 6.1.1 on 2026-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['listener', '-played_at'], name='play_listener_recent'),
        ),
    ]
